myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.create_client, name='create_client'),
    path('create_client', views.create_client, name='create_client'),
    path('clients/<int:client_id>/update/', views.update_client, name='update_client'),
    path('clients/<int:client_id>/delete/', views.delete_client, name='delete_client'),
    path('clients/', views.client_list, name='client_list'),

    # Пути для модели "Товар"
    path('create_product', views.create_product, name='create_product'),
    path('products/<int:product_id>/update/', views.update_product, name='update_product'),
    path('products/<int:product_id>/delete/', views.delete_product, name='delete_product'),
    path('products', views.product_list, name='product_list'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),

    # Пути для модели "Заказ"
    path('create_order', views.create_order, name='create_order'),
    path('orders/<int:order_id>/update/', views.update_order, name='update_order'),
    path('orders/<int:order_id>/delete/', views.delete_order, name='delete_order'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order_products', views.OrderProductListView.as_view(), name='order_product_list'),

    path('clients/<int:client_id>/orders/', views.client_orders, name='client_orders'),
    path('order', views.orders, name='orders'),
    path('client/<int:client_id>/ordered-products/<str:period>/', views.client_ordered_products,
         name='client_ordered_products'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    # path('__debug__/', include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

db_url = 'sqlite:///C:/pythonProject23/myproject/example.db'
engine = create_engine(db_url)
Session = sessionmaker(bind=engine)
session = Session()

Base = declarative_base()


# Определение модели
class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    name = Column(String)
    email = Column(String)


# Создание таблицы в базе данных
Base.metadata.create_all(engine)


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    registration_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    objects = models.Manager()


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='product_photos/', null=True, blank=True)

    def __str__(self):
        return self.name

    objects = models.Manager()


class Order(models.Model):
    customer = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Заказ № {self.pk} - Client: {self.customer.name}"

    objects = models.Manager()


class OrderProduct(models.Model):
    order_ref = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_ref = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"Товар: {self.product_ref.name} - Количество: {self.quantity}"

    objects = models.Manager()

myapp/forms.py
from django import forms
from .models import Client, Product, Order


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'email', 'phone', 'address']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'quantity', 'photo']

    photo = forms.FileField(required=False)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'products', 'total_amount']

    def clean_total_amount(self):
        total_amount = self.cleaned_data['total_amount']
        if total_amount <= 0:
            raise forms.ValidationError("Общая сумма заказа должна быть положительным числом.")
        return total_amount

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Client, Product, Order, OrderProduct
from .forms import ClientForm, ProductForm, OrderForm
from django.views.generic import ListView
from datetime import datetime, timedelta
from django.utils import timezone


# Обработка создания клиента
def create_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('client_list')
    else:
        form = ClientForm()
    return render(request, 'create_client.html', {'form': form})


# Обработка обновления клиента
def update_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect('client_list')
    else:
        form = ClientForm(instance=client)
    return render(request, 'update_client.html', {'form': form})


# Обработка удаления клиента
def delete_client(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    if request.method == 'POST':
        client.delete()
        return redirect('client_list')
    return render(request, 'delete_client.html', {'client': client})


def client_detail(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    return render(request, 'client_detail.html', {'client': client})


def client_list(request):
    clients = Client.objects.all()
    return render(request, 'client_list.html', {'clients': clients})


# Обработка создания товара
def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm()
    return render(request, 'create_product.html', {'form': form})


# Обработка чтения всех товаров
def product_list(request):
    products = Product.objects.all()
    return render(request, 'product_list.html', {'products': products})


# Обработка обновления товара
def update_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'update_product.html', {'form': form})


# Обработка удаления товара
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        product.delete()
        return redirect('product_list')
    return render(request, 'delete_product.html', {'product': product})


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'product_detail.html', {'product': product})


def create_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('order_list')
    else:
        form = OrderForm()

    return render(request, 'create_order.html', {'form': form})


# # Обработка чтения всех заказов
def order_list(request):
    orders = Order.objects.all()
    return render(request, 'order_list.html', {'orders': orders})


# # Обработка обновления заказа
def update_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('order_list')
    else:
        form = OrderForm(instance=order)
    return render(request, 'update_order.html', {'form': form})


# # Обработка удаления заказа
def delete_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        order.delete()
        return redirect('order_list')
    return render(request, 'delete_order.html', {'order': order})


def client_orders(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    orders = Order.objects.filter(client=client)
    return render(request, 'client_orders.html', {'client': client, 'orders': orders})


def order_detail(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    return render(request, 'order_detail.html', {'order': order})


class OrderProductListView(ListView):
    model = OrderProduct
    template_name = 'order_product_list.html'
    context_object_name = 'order_products'

    def get_queryset(self):
        return OrderProduct.objects.all()


def get_date_range(period):
    end_date = timezone.now()

    if period == 'неделя':
        start_date = end_date - timedelta(days=7)
    elif period == 'месяц':
        start_date = end_date - timedelta(days=30)
    elif period == 'год':
        start_date = end_date - timedelta(days=365)
    else:
        # По умолчанию, если не передан поддерживаемый период, используем месяц
        start_date = end_date - timedelta(days=30)

    return start_date, end_date


def get_recent_products(start_date, end_date):
    recent_products = Order.objects.filter(order_date__range=(start_date, end_date)).values_list(
        'products__name', flat=True).distinct()
    return recent_products


def orders(request):
    today = datetime.now().date()
    last_week = today - timedelta(days=7)
    last_month = today - timedelta(days=30)
    last_year = today - timedelta(days=365)

    recent_products = get_recent_products(last_week, today)
    last_month_products = get_recent_products(last_month, today)
    last_year_products = get_recent_products(last_year, today)

    return render(request, 'orders.html', {
        'recent_products': recent_products,
        'last_month_products': last_month_products,
        'last_year_products': last_year_products
    })


def client_ordered_products(request, client_id, period):
    client = Client.objects.get(pk=client_id)
    start_date, end_date = get_date_range(period)

    client_orders_filtered = Order.objects.filter(customer=client, order_date__range=(start_date, end_date))
    ordered_products = Product.objects.filter(order__in=client_orders_filtered).distinct()

    return render(request, 'client_ordered_products.html', {
        'client': client,
        'ordered_products': ordered_products,
        'period': period,
    })

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Мой сайт</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<header>
    <h1>Мой сайт</h1>
    <nav>
        <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/about/">О нас</a></li>
            <!-- Другие пункты меню -->
        </ul>
    </nav>
</header>

<div class="content">
    {% block content %}{% endblock %}
</div>

<footer>
    &copy; 2023 Мой сайт
</footer>
</body>
</html>

myapp/templates/client_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Client List</title>
</head>
<body>
<h1>Client List</h1>

<!-- Таблица для отображения списка клиентов -->
<table>
    <thead>
    <tr>
        <th>Имя</th>
        <th>Электронная почта</th>
        <th>Телефон</th>
        <th>Адрес</th>
        <th>Дата регистрации</th>
    </tr>
    </thead>
    <tbody>
    {% for client in clients %}
    <tr>
        <td>{{ client.name }}</td>
        <td>{{ client.email }}</td>
        <td>{{ client.phone }}</td>
        <td>{{ client.address }}</td>
         <td>{{ client.registration_date }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

myapp/templates/client_ordered_products.html
{% extends "base.html" %}

{% block content %}
  <h2>Список заказанных товаров клиента {{ client.name }}</h2>
  <h3>За последние {{ period }}:</h3>
  <ul>
    {% for product in ordered_products %}
      <li>{{ product.name }}</li>
    {% endfor %}
  </ul>
{% endblock %}

myapp/templates/create_client.html
<!-- Форма для создания клиента -->
<form method="POST" action="{% url 'create_client' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать клиента</button>
</form>

<!-- Таблица для отображения списка клиентов -->
<table>
    <thead>
    <tr>
        <th>Имя</th>
        <th>Электронная почта</th>
        <th>Телефон</th>
        <th>Адрес</th>
    </tr>
    </thead>
    <tbody>
    {% for client in clients %}
    <tr>
        <td>{{ client.name }}</td>
        <td>{{ client.email }}</td>
        <td>{{ client.phone }}</td>
        <td>{{ client.address }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

myapp/templates/create_order.html
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_client">customer:</label>
        {{ form.customer }}
    </div>
    <div class="form-group">
        <label for="id_product">products:</label>
        {{ form.products }}
    </div>
    <div class="form-group">
        <label for="id_total_amount">total_amount:</label>
        {{ form.total_amount }}
    </div>
    <button type="submit">Создать заказ</button>
</form>

myapp/templates/create_product.html
<!-- create_product.html -->
<form method="POST" action="{% url 'create_product' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_name">Name:</label>
    <input type="text" id="id_name" name="name" required>

    <label for="id_price">Price:</label>
    <input type="number" id="id_price" name="price" step="0.01" required>

    <label for="id_description">Description:</label>
    <textarea id="id_description" name="description" required></textarea>

    <label for="id_quantity">Quantity:</label>
    <input type="number" id="id_quantity" name="quantity" required>

    <label for="id_image">Image:</label>
    <input type="file" id="id_image" name="photo" accept="image/*" required>

    <button type="submit">Create</button>
</form>

myapp/templates/order_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Order Detail</title>
</head>
<body>
<h1>Order Detail</h1>

<p><strong>Order Number:</strong> {{ order.order_number }}</p>
<p><strong>Client:</strong> {{ order.client.name }}</p>
<p><strong>Order Date:</strong> {{ order.order_date }}</p>


<h2>Ordered Products</h2>
<ul>
    {% for product in order.products.all %}
    <li>{{ product.name }} - ${{ product.price }}</li>
    {% endfor %}
</ul>

</body>
</html>

myapp/templates/order_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Order List</title>
</head>
<body>
<h1>Order List</h1>

<!-- Таблица для отображения списка заказов -->
<table>
    <thead>
    <tr>
        <th>Order Number</th>
        <th>Client</th>
        <th>Order Date</th>

    </tr>
    </thead>
    <tbody>
    {% for order in orders %}
    <tr>
        <td><a href="{% url 'order_detail' order.id %}">{{ order.order_number }}</a></td>
        <td>{{ order.client.name }}</td>
        <td>{{ order.order_date }}</td>

    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

myapp/templates/order_product_list.html
{% for order_product in order_products %}
<p>Товар: {{ order_product.product_ref.name }} - Количество: {{ order_product.quantity }}</p>
{% endfor %}

myapp/templates/orders.html
<!DOCTYPE html>
<html>
<head>
    <title>Список заказов</title>
</head>
<body>
<h1>Список заказов</h1>
<h2>За последние 7 дней</h2>
<ul>
    <!-- Здесь можно использовать скрипт или цикл, чтобы выводить каждый элемент списка заказов -->
    <li>Наименование товара 1</li>
    <li>Наименование товара 2</li>
    <li>Наименование товара 3</li>
    <!-- и так далее -->
</ul>

<h2>За последние 30 дней</h2>
<ul>
    <!-- Здесь можно использовать скрипт или цикл, чтобы выводить каждый элемент списка заказов -->
    <li>Наименование товара 4</li>
    <li>Наименование товара 5</li>
    <li>Наименование товара 6</li>
    <!-- и так далее -->
</ul>

<h2>За последний год</h2>
<ul>
    <!-- Здесь можно использовать скрипт или цикл, чтобы выводить каждый элемент списка заказов -->
    <li>Наименование товара 7</li>
    <li>Наименование товара 8</li>
    <li>Наименование товара 9</li>
    <!-- и так далее -->
</ul>
</body>
</html>

myapp/templates/product_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Product Detail</title>
</head>
<body>
<h1>Product Detail</h1>

<p><strong>Name:</strong> {{ product.name }}</p>
<p><strong>Price:</strong> ${{ product.price }}</p>
<p><strong>Description:</strong> {{ product.description }}</p>
<p><strong>Quantity:</strong> {{ product.quantity }}</p>


<p><strong>Image:</strong></p>
<img src="{{ product.photo.url }}" alt="{{ product.name }}">

</body>
</html>

myapp/templates/product_list.html
<!-- Таблица для отображения списка продуктов -->
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Date Added</th>
        <th>Image</th>  <!-- Добавляем столбец для изображения -->
    </tr>
    </thead>
    <tbody>
    {% for product in products %}
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.quantity }}</td>
        <td>{{ product.date_added }}</td>
        <td><img src="{{ product.image.url }}" alt="{{ product.name }}" width="100"></td>
        <!-- Отображаем изображение продукта -->
    </tr>
    {% endfor %}
    </tbody>
</table>

myapp/templates/update_client.html
```html
<!DOCTYPE html>
<html>
<head>
    <title>Update Client</title>
</head>
<body>
<h1>Update Client</h1>

<!-- Форма для обновления данных клиента -->
<form method="POST" action="{% url 'update_client' client_id %}">
    {% csrf_token %}

    <!-- Поля для изменения данных клиента -->
    <input type="text" name="name" placeholder="Name" value="{{ client.name }}">
    <input type="text" name="email" placeholder="Email" value="{{ client.email }}">

    <button type="submit">Update</button>
</form>
</body>
</html>

myapp/templates/update_order.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Order</title>
</head>
<body>
<h1>Update Order</h1>

<!-- Форма для обновления данных заказа -->
<form method="POST" action="{% url 'update_order' order_id %}">
    {% csrf_token %}

    <!-- Поля для изменения данных заказа -->
    <input type="text" name="customer_name" placeholder="Customer Name" value="{{ order.customer_name }}">
    <input type="text" name="product_name" placeholder="Product Name" value="{{ order.product_name }}">
    <input type="number" name="quantity" placeholder="Quantity" value="{{ order.quantity }}">

    <button type="submit">Update</button>
</form>
</body>
</html>